services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.10"
    environment:
      - "ELASTIC_PASSWORD=secret"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200"
      - "9300"
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=mydatabase"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
    ports:
      - "3306"
  redis:
    image: "redis:latest"
    ports:
      - "6379"

  observability:
    container_name: observability
    image: grafana/otel-lgtm
    ports:
      - 3001:3000 # Grafana
      - 4317:4317 # OLTP gRPC Receiver
      - 4318:4318 # OLTP HTTP Receiver
